# Generated by Django 4.0.4 on 2022-07-12 07:42

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_vid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(default='none', max_length=100)),
                ('vid_type', models.CharField(choices=[('1', 'virals'), ('2', 'movies'), ('3', 'shortfilms'), ('4', 'webshows')], default='1', max_length=20)),
                ('vid_cotegory', models.CharField(choices=[('1', 'action'), ('2', 'comedy'), ('3', 'suspence,drama thrils'), ('4', ' biopic')], default='1', max_length=20)),
            ],
        ),
    ]
