# Generated by Django 4.0.6 on 2022-07-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home_vid',
            new_name='Home',
        ),
    ]
