# Generated by Django 4.0.6 on 2022-07-14 11:40

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_home_vid_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(default='none', max_length=100)),
                ('vid_cotegory', models.CharField(choices=[('1', 'action'), ('2', 'comedy'), ('3', 'suspence,drama thrils'), ('4', ' biopic')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shortfilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(default='none', max_length=100)),
                ('vid_cotegory', models.CharField(choices=[('1', 'action'), ('2', 'comedy'), ('3', 'suspence,drama thrils'), ('4', ' biopic')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Viral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(default='none', max_length=100)),
                ('vid_cotegory', models.CharField(choices=[('1', 'action'), ('2', 'comedy'), ('3', 'suspence,drama thrils'), ('4', ' biopic')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Webshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(default='none', max_length=100)),
                ('vid_cotegory', models.CharField(choices=[('1', 'action'), ('2', 'comedy'), ('3', 'suspence,drama thrils'), ('4', ' biopic')], default='1', max_length=20)),
            ],
        ),
    ]
